language: python
python:
- '3.6'
- '3.7'
matrix:
  include:
  - python: 3.7
    dist: xenial
before_install:
- pip install poetry
install:
- poetry install -v
- pip install tox-travis
script:
- tox
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- npm run-script build --prefix windmill/http/app/
- poetry build
deploy:
  provider: script
  script: poetry publish
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.7"
env:
  global:
  - secure: Ggaih56Kk9n01HBc2U3t/V6xZ9Wcgz53/WODJIMgIRQrHjC3BFKB8OYbsZluFSFJnFBRRCTlgu40Ns6iuTMerK9sJWeiYgQCravMsxTVca2FjefXn/e9grhvp2HKvWwL06NK7clZKWKR9bXwaU5SpxNoSXhR3Rizd4cwPESjopKZdKwgkxLGQMPRotkaAMOunarfVWHRwFmyrn8JEYwezJTQPrajPT2xsZvFt50eyy+oeDfDttzFljMo4nQ49DIr5dX2xRZPoVSa2Jj5LdMqx3d4baeLd9bROCMnbTTozrR52AlVrjy6M7Ed/23tAbblkjIlvyXJtsiTcH5EW5C1UlkahlMhaGjeWcv4HD8w2+ZjLo3/KIjFEEpfzwAGENEPp+x8aQMzKeenKIxxCQkH92dmNxY0ANCXaXXrVkzzxFbkDMfvtH/ZCoSy7Wswpkq6PkcPsuf4oR6nHl7pxlVAM/AFLaIEQg7o02gMxPwqLXXN+6XsHuCBRSS3kN1B5GP8XR1gW20MyanT3tllAi1bjfpYCXivxAtOA6fxHPjyQjFubtp73v4TJpASXwq85dTPo7h71XHJiwX9qvoccqUx3hmMNdzH2F1uI+AlP42Upi62MQJ2VNd3RSUtZiVXX0ocffnagBRS/23xwkhEww0kyasev+Gy0rxdtFfhdA5yJ78=
  - secure: DL4YmNCV3w69vypDBPZFe07DhaxmhX4GqELU12lJ1pKvUUiMvdCjW0sO0ea9jTXgmFB4XqURCARBUqOxvxG2hepD5gTTCKqMletc/7Rta8wm62iJnKi0BOwvgJqZhYbgfPNuu/1M3Qk651CEoZ5a8tq9z9hjOeqYxX4sHeJMKNQzs7C2PJmUm9ITkO/aJU8YRgaj9G2sei5if9EzPDC/wAm4lVJ39uBDkQisNPu12eSaWzMCyRp7Cjzo7Md83r7yukMPTBfwKQ9bv3RuVxwV3Togjq/FHSRMOH0aV86ODdDRcQ5E/8YC1PhmlfV9JxHNFTG8tQSOZ+tJvIf3XH6mcEx4DGCeKozJxSf/pg1prJU6h1qVyOLFCmB2MrZeOvg3tH3eF5yOkjDF09yFqNNOTjlZNfN7GaNdtd1BOVSwUqVmCrKaKPVMaskNXzBLvKxmNPumpIpfiiXmPOLbsGLgx1kcpnVQHStoL/QRDeTKqgx0JXxx3c9ix3oYMsB8ANJ6mcXHf3KxiAWc0yvovJudyzlOLtakIQHExRIV6IAnKt3rrIAnipDpUUbZJkRsDjSIut8sdm4a8efET51uXB+nOFV2POHYIuHCuTtAps4w2thiwcJ8ZMQ7hgmnZEGRbrerNvc2S/2k1hsJxRq4WGXg7hG7jlE6/D6/J1Z1fX7CgkU=
